### ISSUE TITLE
tf version?

### ISSUE THREAD

**Issue by yunhenk** [jihunchoi/sequential-denoising-autoencoder#1]
Which version is tf in this project ,TF 1.7 seems doesn't work.Thanks

**Comment by jihunchoi** [comment]
Sorry for not specifying the version.
I implemented this quite a long ago, and don't remember the exact version but I'm sure one of the stale versions was used (maybe 0.9 or 0.8?).
It's been a while since I used TF last time, but I think the code might run with not much modification.

**Comment by yunhenk** [comment]
@jihunchoi Thanks for your reply. I run this code successfully with tf 1.0.

**Comment by jihunchoi** [comment]
Good! I added the version information to the readme.
